name: qr_reader
description: Implementation of the QR scanner listener that handles output as keyboard events.
version: 0.0.1
homepage: https://bakersoft.de/de/

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter: